seccionando

diff --git a/.github/workflows/poc.yml b/.github/workflows/poc.yml
--- a/.github/workflows/poc.yml
+++ b/.github/workflows/poc.yml
@@ -68,17 +68,17 @@ jobs:
           if [ "$PR_NUMBER" != "null" ]; then
             echo "PR creado exitosamente: #$PR_NUMBER"
             
-            # Agregar label BORRADOR
-            curl -s -L -X POST \
-              -H "Authorization: token $GITHUB_TOKEN" \
-              -H "Accept: application/vnd.github.v3+json" \
-              -H "Content-Type: application/json" \
-              https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels \
-              -d '{"labels":["BORRADOR"]}'
+          #   # Agregar label BORRADOR
+          #   curl -s -L -X POST \
+          #     -H "Authorization: token $GITHUB_TOKEN" \
+          #     -H "Accept: application/vnd.github.v3+json" \
+          #     -H "Content-Type: application/json" \
+          #     https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels \
+          #     -d '{"labels":["BORRADOR"]}'
               
-            echo "✅ Label BORRADOR agregado al PR #$PR_NUMBER"
-          else
-            echo "❌ Error al crear PR Pinche Wey:"
-            cat pr_response.json
-            exit 1
-          fi
+          #   echo "✅ Label BORRADOR agregado al PR #$PR_NUMBER"
+          # else
+          #   echo "❌ Error al crear PR Pinche Wey:"
+          #   cat pr_response.json
+          #   exit 1
+          # fi
